apiVersion: v1
kind: Secret 
metadata:
  name: backend-secret
  namespace: tmb13be
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGJiMTMtc2VydmljZS50bWIxM2RiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
  # mongodb://mongodbb13-service.tmb13db.svc.cluster.local:27017